### ISSUE TITLE
Just had a small layout question

### ISSUE THREAD

**Issue by keegho** [shprink/wphc#2]
Hello Julien;
 I just had a small issue and i needed your advice.
I wanted to change the layout of the posts themselves and make them a small thumbnail on the left and the title + some text of the main post on its right.
Which templates do you advice me to change in? Or is there a ready made layout that we can implement? I uploaded the screen shot of the layout.
And the code itself of the posts layout.

cordialement;
Kegham K.

![screen shot 2016-04-24 at 5 09 32 pm](https://cloud.githubusercontent.com/assets/16656424/14768334/098f1504-0a48-11e6-9f55-30b9bbd764b2.png)

This is the code:

```
<ion-view view-title="News">
  <ion-content>
  <ion-refresher on-refresh="doRefresh()"></ion-refresher>

  <ion-list can-swipe="listCanSwipe">

        <ion-item class="item-icon-right item-thumbnail-left" ng-repeat="post in posts track by $index" href="#/app/posts/{{post.id}}" track>

             <img ng-src="{{post.better_featured_image.source_url}}" class="customized_image" />
            <h2 ng-bind-html="post.title.rendered"></h2>
            <p ng-if="post.excerpt.rendered" ng-bind-html="post.excerpt.rendered"></p>
            <i class="icon ion-chevron-right icon-accessory"></i>
            <p><span am-time-ago="post.date"></span></p>
            <ion-option-button class="button-positive"
                       ng-click="share(item)">
      Share
    </ion-option-button>
        </ion-item>

    </ion-list>

    <ion-infinite-scroll
    ng-if="moreDataExists()"
    on-infinite="loadMore()"
    distance="1%"
    immediate-check="false">
  </ion-infinite-scroll>

  </ion-content>
</ion-view>
```

**Comment by shprink** [comment]
You can do that with WPHC by overwriting the posts template.

The docs to do that is here: https://github.com/shprink/wordpress-hybrid-client/blob/develop/CONFIGURATION.md#overwriting-existing-templates

The file you need to modify is here: https://github.com/shprink/wordpress-hybrid-client/blob/develop/lib/templates/module/posts-list.html

Good luck
